### ISSUE TITLE
Last PR #423: Fix Economist/NYTimes/Caixin Global/Nrc.nl/Newcastle Herald/Toronto Star/Australian Financial Review/Globe and Mail/LeParisien.fr/Statista/Bloomberg Quint/Handelsblatt & add LesEchos.fr/The Athletic/Tech in Asia/Scribd/Lecho.be

### ISSUE THREAD

**Issue by magnolia1234** [magnolia1234/bypass-paywalls-firefox-clean#1]
Allow cookies for sites with Googlebot user-agent.

Fix Economist (Javascript/cookies); mobile menu is no longer working.

Fix NYTimes (layout)
Block specific Javascript instead of Googlebot user-agent.

Fix Caixin Global
Fix for subscription messages while scrolling multiple articles on one page.

Fix Nrc.nl (paywall)
New paywall-overlay for specific articles (test?).

Fix Newcastle Herald (+ new domain)

Fix Toronto Star (enable Javascript)
Fix Australian Financial Review (enable Javascript/photos)
Fix Globe and Mail (enable Javascript/photos, no video and photo gallery though)
Update: clear in-memory cache for Webrequest to work correctly (block or not block specific G&B-Javascript).

Fix LeParisien.fr (block TinyPass paywall)

Fix Statista & Bloomberg Quint (manifest)
Missing in manifest.json (since added) ...

Fix Handelsblatt (Googlebot)

Add LesEchos.fr (block TinyPass paywall-script)
Already in Chrome extension.

Add Lecho.be
Already in Chrome extension.

Add The Athletic @iscreamcoke

Add Tech in Asia @winstonma

@iscreamcoke
Add Scribd (unblur text of documents)
Fix for MIT Tech Review (click the button to expand article and remove banner)
Fix banners on TheTimes.co.uk, Bloomberg, Asia Nikkei, Haaretz.com & Hbr.org

**Comment by qnoum** [comment]
is business insider broken or is it only by me?

**Comment by magnolia1234** [comment]
Last v1.6.3.5 should work just fine though.
