### ISSUE TITLE
Law360

### ISSUE THREAD

**Issue by kchio0331** [magnolia1234/bypass-paywalls-firefox-clean#10]
Hello,

Can you please make this website paywall free? Law360 is a legal news website. When I click on an article at https://www.law360.com/articles/1244143/weinstein-says-da-script-demeans-women-in-5-hour-closing, it is asking me for pay. Do you know how to make it free? 

Thank you.

**Comment by magnolia1234** [comment]
Hard paywall (subscription-only).
