### ISSUE TITLE
wsj.com not working on firefox for android

### ISSUE THREAD

**Issue by vic958420** [magnolia1234/bypass-paywalls-firefox-clean#11]
![Screenshot_20200217-231641_Firefox](https://user-images.githubusercontent.com/38735851/74704378-39a62200-51de-11ea-9e82-dccdfc074cdd.png)

**Comment by magnolia1234** [comment]
You're using release v1.6.4.3?
I'm also having issues with my unsigned test-version (from master-zip), but the latest release is working fine though.
Firefox for Android is more prone to timing-issues (no problems on desktop version).

**Comment by vic958420** [comment]
issue fixed by uninstalling the user agent switcher extension

**Comment by magnolia1234** [comment]
Make sense, WSJ-fix uses Googlebot.
