### ISSUE TITLE
small glitch (sites not ticked in options)

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-firefox-clean#12]
when i updated to the new version, for some reason the updated sites were not ticked in the options and i had to go to "Select all" to tick everything. it's a minor thing but it can be hard to notice if you don't pay attention.

**Comment by magnolia1234** [comment]
I can't reproduce this issue though.
You didn't by accident click the button 'select none' first?

**Comment by danielgruber8** [comment]
no i didnt select none, because the other sites remained ticked and the updated ones werent
fyi i use ubuntu 16.04 and downloaded the new xpi file in firefox 72.0.2 64 bit to update

**Comment by magnolia1234** [comment]
Ah I see, just the new ones were unticked.
That's normal though because they aren't in the local storage yet.
Some time ago I added an extra line in the readme about this.
