### ISSUE TITLE
Difference between your repo and the one by iamadamdev

### ISSUE THREAD

**Issue by armsp** [magnolia1234/bypass-paywalls-firefox-clean#2]
Not really an issue here, just curious to know what is the major difference between your repo and the repo by [iamadamdev](https://github.com/iamadamdev/bypass-paywalls-firefox).

**Comment by magnolia1234** [comment]
Adam hasn't updated since a month, but 75% of the commits where provided by me anyway since 3 months.
Major refactoring, lots of bugs fixed and sites added to json-file ( easier maintenance).
You're welcome :-)

**Comment by armsp** [comment]
Thanks. Closing this issue.
