### ISSUE TITLE
Website Request: https://www.geelongadvertiser.com.au

### ISSUE THREAD

**Issue by TesterMan247** [magnolia1234/bypass-paywalls-firefox-clean#21]
I tried the site with v1.6.6.1, but it didn't work.

Therefore, please add the following website:
https://www.geelongadvertiser.com.au

Thank you.

**Comment by magnolia1234** [comment]
You could use a custom site-fix with Googlebot.

**Comment by magnolia1234** [comment]
Local newspapers by custom sites.

**Comment by TesterMan247** [comment]
> Local newspapers by custom sites.

What exactly do you mean?
What is the solution?
Will the next release will fix it or something?

**Comment by magnolia1234** [comment]
You can add the local site with the 'custom sites'-option and check the googlebot-box.
Also possible in current release.

**Comment by TesterMan247** [comment]
I just tried in v1.6.6.2, but it still doesn't work.

PS: I can see the Custom Sites in the addon options, but how can I add sites to it?
Its got no add or remove site button or anything like that...

**Comment by TesterMan247** [comment]
The ancient Anti-Paywall 0.9.2 add-on can get this site working normally, so I'm sure you can too, like you've done with https://github.com/magnolia1234/bypass-paywalls-firefox-clean/issues/19

Thanks.

**Comment by magnolia1234** [comment]
User-interface is in development (new commit, but not yet in release).
But now you can get to custom settings by clicking on icon (desktop) or BPC-item in FF-menu (Android).

**Comment by magnolia1234** [comment]
> The ancient Anti-Paywall 0.9.2 add-on can get this site working normally, so I'm sure you can too, like you've done with #19
> 
> Thanks.

You're stubborn aren't you? ;-)
I'm not going to add every single local newspaper if you can add them yourself with custom sites.

**Comment by TesterMan247** [comment]
> > The ancient Anti-Paywall 0.9.2 add-on can get this site working normally, so I'm sure you can too, like you've done with #19
> > Thanks.
> 
> You're stubborn aren't you? ;-)
> I'm not going to add every single local newspaper if you can add them yourself with custom sites.

Please just add this as I want your site to work with AT LEAST everything the Anti-Paywall 0.9.2 add-on does, so that I can stop using that.

**Comment by danielgruber8** [comment]
Yes there are quite a few additional sites there which would be nice to merge :)

https://github.com/nextgens/anti-paywall

**Comment by TesterMan247** [comment]
> 
> 
> Yes there are quite a few additional sites there which would be nice to merge :)
> 
> https://github.com/nextgens/anti-paywall

It sure would be, but I'll be content with just this additional sit....

**Comment by magnolia1234** [comment]
> Yes there are quite a few additional sites there which would be nice to merge :)
> 
> https://github.com/nextgens/anti-paywall

Be more specific?
Lots of the 'missing' sites are redirects or don't have a paywall (anymore).

**Comment by TesterMan247** [comment]
> 
> 
> > Yes there are quite a few additional sites there which would be nice to merge :)
> > https://github.com/nextgens/anti-paywall
> 
> Be more specific?

OK. Like I have already said.....https://www.geelongadvertiser.com.au

Thanks :-)

**Comment by magnolia1234** [comment]
> OK. Like I have already said.....https://www.geelongadvertiser.com.au
> Thanks :-)

How old are you, 12? ;-)
As I said before, use custom sites for this local website with Googlebot-fix.

**Comment by TesterMan247** [comment]
> > OK. Like I have already said.....https://www.geelongadvertiser.com.au
> > Thanks :-)
> 
> How old are you, 12? ;-)
> As I said before, use custom sites for this local website with Googlebot-fix.

OK Fine.
Please tell me how to add it exactly....

**Comment by magnolia1234** [comment]
Check new release v1.6.6.3.
