### ISSUE TITLE
https://www.wiscnews.com/ Major news site covering 8 papers/news in WI

### ISSUE THREAD

**Issue by bkayrac** [magnolia1234/bypass-paywalls-firefox-clean#23]
Hitting the limit, and then copying the link and pasting it into a private window allows you to read the article. So I think that makes it workable with your extension, but not sure.

**Comment by bkayrac** [comment]
I should add, I just saw the custom site option. I was able to figure it out, and add this myself. But it may still benefit anyone from WI to have it added to the default :)

**Comment by magnolia1234** [comment]
> I should add, I just saw the custom site option. I was able to figure it out, and add this myself. But it may still benefit anyone from WI to have it added to the default :)

Indeed, simple article-limit (by local storage setting).
Maybe I'll add it later (to local USA news).

**Comment by magnolia1234** [comment]
Local newspapers by custom sites (if possible).
