### ISSUE TITLE
NK News no longer works as of February 27 ... But with an unusual block message

### ISSUE THREAD

**Issue by WanTjhenA340** [magnolia1234/bypass-paywalls-firefox-clean#24]
So I was trying to access NKNews again after about a few days since my last access (during which your extension worked fine - I've skimmed quite a few articles of interest there). When I accessed it again earlier today though, the paywall hits back, but with a different message in which it explained that 'Your NK PRO account has expired !' or something like that, no offers for subscription or anything (oh, and this type of account - NK PRO - is pretty much inaccessible to the general public since the only option to 'renew' it is through personal inquiries with NK News itself). It doesn't help either that the general subscription fees are really hefty for a news site and even then, the at least $3.84 weekly payment only allows access to the 'regular' articles.

Turning off uBlock generates the same results. Now, considering how notoriously strict this newssite's paywall is, to be honest I don't know if there's a remedy for this and should there be nothing that can be done to bypass this I'm going to just accept it, but I'd highly appreciate it if you can take a look at this. Thank you (and to the NKNews management, F*** you and your disgusting stance on paywalls)

![Screenshot_20200226-172240](https://user-images.githubusercontent.com/20898244/75600359-18e4a300-5ae1-11ea-9cac-1bc82826fc3b.png)

**Comment by magnolia1234** [comment]
Hard paywall now, they closed the Googlebot-fix loophole.

**Comment by WanTjhenA340** [comment]
Darn ... A really a*****e way of NK News dealing with this sorta thing. Not even trial articles (or NK Pro), and at least 3.84 USD per week just to read the BASIC articles (as a student I certainly have many more important things to be paid with that money). This is the only website I know of that charges this high for their web contents.

Thanks for allowing a much wider audience to read their articles when it was still allowed though. Let's see if things can change again someday

**Comment by danielgruber8** [comment]
This article seems to load fine once NKnews is unticked.
https://www.nknews.org/2020/01/kim-jong-uns-plenum-speech-experts-react/

**Comment by danielgruber8** [comment]
Also is Googlebot the only loophole... what about other search engines e.g. Bing or DuckDuckGo etc?

**Comment by magnolia1234** [comment]
Some articles are freely available.
If you find another search-engine that works, let me know.
