### ISSUE TITLE
Issue with https://kayosports.com.au when add-on enabled

### ISSUE THREAD

**Issue by TesterMan247** [magnolia1234/bypass-paywalls-firefox-clean#25]
I noticed an issue with the site: https://kayosports.com.au

With the add-on v1.6.6.1 enabled, the Kayo Sports site does not start some videos correctly, and also some pages don't load correctly.

Also, once you've logged into Kayo Sports, when the add-on is enabled, you leave Kayo Sports and come back to it, you always have to log back in again.

With the add-on enabled, it seems to lose the persistent login that normally works well when the add-on is disabled.

When this add-on is disabled, the Kayo Sports site works perfectly.

I've only just noticed issues with this website now, so who knows how many other sites also has issues.
Your add-on needs to just look at and react with the sites you support, and not generically mess with other sites, otherwise there will always be issues with other non-related sites all the time.

For example, https://kayosports.com.au shouldn't even be looked at, it should just be ignored with no messing with it whatsoever.

**Comment by spoetnik412** [comment]
BPC shouldn't be active on this domain, unless you've added custom sites.
If so, can you copy the json-text (in {}).
There could be an issue with an empty domain (matches with all sites).
PS I can't reproduce issues on subscription sites (also for your thelott.com issue).

**Comment by magnolia1234** [comment]
BPC shouldn't be active on this domain, unless you've added custom sites.
If so, can you copy the json-text (in {}).
There could be an issue with an empty domain (matches with all sites).
PS I can't reproduce issues on subscription sites (also for your thelott.com issue).

**Comment by magnolia1234** [comment]
Still no issue for me on other subscription-sites.

**Comment by TesterMan247** [comment]
Please don't close these issues.
They happen 100% of the time, and I am able to reproduce it 100% of the time.

Its a slap in the face to just close these issues saying you cannot reproduce it, when it clearly happens and is an ongoing issue.

You'll need to perhaps Teamviewer into my machine to see the issue someday.

**Comment by magnolia1234** [comment]
You're using the new custom-sites feature though (if so include the json-text here)?
Or a publicly accessible site which gives the same issues (for you)?

**Comment by TesterMan247** [comment]
> You're using the new custom-sites feature though (if so include the json-text here)?
> Or a publicly accessible site which gives the same issues (for you)?

I don' even know how to put in custom sites.
These two sites are publicly accessable sites.....

**Comment by magnolia1234** [comment]
>I don' even know how to put in custom sites.
>These two sites are publicly accessible sites.....

Sure, but for kayosports.com.au you need a payed account.
Fixed in latest release v1.6.6.2 (tested on thelott.com).

**Comment by TesterMan247** [comment]
> > I don' even know how to put in custom sites.
> > These two sites are publicly accessible sites.....
> 
> Sure, but for kayosports.com.au you need a payed account.
> Fixed in latest release v1.6.6.2 (tested on thelott.com).

So you DID find a problem on thelott site?
What was the issue exactly?

As for the Kayo site...yes it is paid for, but you can sign up and get 14 days absolutely free.

**Comment by magnolia1234** [comment]
BPC fixed for both sites.

**Comment by TesterMan247** [comment]
What was the issue exactly?

**Comment by TesterMan247** [comment]
Issue has been resolved on v1.6.6.2.
Thanks.

**Comment by magnolia1234** [comment]
Local storage was deleted, but not the cookies though.
