### ISSUE TITLE
Issue with site: https://www.thelott.com

### ISSUE THREAD

**Issue by TesterMan247** [magnolia1234/bypass-paywalls-firefox-clean#26]
The add-on v1.6.6.1 is having issues with the site: https://www.thelott.com

The amount of money in my account is always shown as $0 until I click on the money, and then the proper money amount is shown.

Also, when I buy  anything and add it to the cart, then go to the cart to buy it, it shows that there are no items in the cart.
So in other words, I buy a lotto, it gets added to the cart. However, when I try and buy it, it shows no tickets are there.

Again, with the add-on disabled, the site works perfectly the way it should...

I've only just noticed issues with this website now, so who knows how many other sites also has issues.
Your add-on needs to just look at and react with the sites you support, and not generically mess with other sites, otherwise there will always be issues with other non-related sites all the time.

For example, https://www.thelott.com shouldn't even be looked at, it should just be ignored with no messing with it whatsoever.

**Comment by magnolia1234** [comment]
See https://github.com/magnolia1234/bypass-paywalls-firefox-clean/issues/25

**Comment by magnolia1234** [comment]
Fixed in latest release v1.6.6.2 (tested on thelott.com).
Btw site has bug (after restart of browser you're logged out, but the purchases in chart are still visible).

**Comment by TesterMan247** [comment]
> Fixed in latest release v1.6.6.2 (tested on thelott.com).
> Btw site has bug (after restart of browser you're logged out, but the purchases in chart are still visible).

Thanks.
I'll test it out soon.
Also, how can you get to the cart if you're logged out?

**Comment by magnolia1234** [comment]
Right, you'll have to ask them ;-)

**Comment by TesterMan247** [comment]
Tested v1.6.6.2 and the issue has now been fixed.
Thanks a lot.

PS: What exactly was the issue?

**Comment by magnolia1234** [comment]
Local storage (cart) was deleted, but not the cookies (login).
