### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-firefox-clean#28]
UBlock Origin shows a little square icon as to the number of adverts blocked when visiting a site

Can BPC do a little red tag or something similar so I know if its active when I visit a particular site?

**Comment by magnolia1234** [comment]
Would be nice indeed.
An on-off switch on the icon was suggested before too.

**Comment by magnolia1234** [comment]
Added in release v1.6.6.3.

**Comment by danielgruber8** [comment]
thanks for adding the icon :)
maybe also a yellow exclamation icon when there is a new version :)
yes on-off switch would be nice too :)

**Comment by magnolia1234** [comment]
Update notification might be usefull for chrome extension from unpacked folder.
On-off switch more complicated since custom sites (for now use options).
