### ISSUE TITLE
Site request: il foglio

### ISSUE THREAD

**Issue by Thalon77** [magnolia1234/bypass-paywalls-firefox-clean#29]
Don't know if it's possible to add it, but I would like to see ilfoglio.it in the list of supported sites, here is [a direct link of one of their articles](https://www.ilfoglio.it/giustizia/2020/02/27/news/lannutti-m5s-condannato-per-aver-diffamato-la-banca-ditalia-di-nuovo-303906/?underPaywall=true) protected by paywall, don't know if that paywall is weak enough to be eluded.

**Comment by magnolia1234** [comment]
Premium articles have a hard paywall, it seems.
