### ISSUE TITLE
Better UI needed for adding Custom Sites

### ISSUE THREAD

**Issue by TesterMan247** [magnolia1234/bypass-paywalls-firefox-clean#30]
While adding Custom Sites, instead of the two input boxes being empty, like this: https://imgur.com/pV35RO5 please put in default help text such as "Test Site" and "www.testsite.com", such as shown here: https://imgur.com/VRD998S.

**Comment by magnolia1234** [comment]
Read the manual at the top.

**Comment by TesterMan247** [comment]
> Read the manual at the top.

I did.

It's not clear, thats why I suggested what I did.

I thought you'd love the idea, but you're turning more into Adam every single day.
Seems you want no feedback or comments at all...

**Comment by magnolia1234** [comment]
Ha ha, sorry for not recognizing my privilege of catering to your sometimes nagging 'requests' (about adding a local Australian site) ;-)
But you figured out adding a custom site anyway?
PS there is a not so subtle difference between comments/feature requests and demands ...
But you can always try your luck with Adam though ;-)
