### ISSUE TITLE
Aftonbladet

### ISSUE THREAD

**Issue by niklaspivic** [magnolia1234/bypass-paywalls-firefox-clean#32]
This is a Swedish magazine.

These settings actually worked when I just tried them in your add-in:

`{"Aftonbladet":{"domain":"aftonbladet.se","googlebot":"1","block_javascript":"1"}}`

**Comment by magnolia1234** [comment]
Nice, you managed to add a custom site.
I'll add Aftonbladet to the add-on (just the Googlebot-fix is enough though).
