### ISSUE TITLE
american affairs journal 

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-firefox-clean#34]
Can you please remove the subscribe overlay? :

You are currently reading 0 out of your 1 free articles this month. Please subscribe to receive unlimited access to this site.
Already have an account? Sign In.

**Comment by magnolia1234** [comment]
You can block the top-banner with this custom rule in your adblocker though:
americanaffairsjournal.org##.paywall-notification-bar-wrapper

**Comment by magnolia1234** [comment]
Banner blocked in latest release.
