### ISSUE TITLE
Corriere della sera

### ISSUE THREAD

**Issue by tonicofonico** [magnolia1234/bypass-paywalls-firefox-clean#36]
Corriere della Sera is not working
https://www.corriere.it/cronache/20_marzo_08/coronavirus-post-choc-prof-a-chi-rientra-zone-rosse-mafie-impongano-quarantene-domiciliari-87f1e2f8-6153-11ea-8f33-90c941af0f23.shtml

**Comment by magnolia1234** [comment]
Is working just fine for me though.
Are you using the lp-version (limited-permissions)?
If so, it might be possible that the permission for blocking the paywall-script is missing.

**Comment by magnolia1234** [comment]
* works only fine in combination with uBlock Origin.
I'll look into it.

**Comment by magnolia1234** [comment]
I've fixed it for Chrome, but on Firefox there seem to be issues with the Corriere-site (timeout on images etc.).

**Comment by Kal999** [comment]
Hi, I confirm I have the same issue: Firefox, uBlock Origin but site not working.
Thank you!

**Comment by magnolia1234** [comment]
Randomly Corriere works for me, but then a day later it doesn't.

**Comment by Kal999** [comment]
I hope you can fix it!

**Comment by tonicofonico** [comment]
seems is not fixed

**Comment by magnolia1234** [comment]
I'll update the fix for Corriere in a moment, it works for me.
On Firefox ( without uBlock) the site can be slow at times and will delay the images.

**Comment by magnolia1234** [comment]
When your Firefox is slow then activate these filters in your adblocker (uBlock Origin):
hpHosts’ Ad and tracking servers
Or in my filters ||cdn4.userzoom.com^
AdGuard Tracking Protection
Or in my filters ||lp4.io^

**Comment by magnolia1234** [comment]
Check new release v1.6.6.5.
Lots of strength with the Corana-crisis in Italy.

**Comment by Kal999** [comment]
Hi magnolia1234 and thank you for all your work. Really really appreciated.
I added these filters to uBlock Origin My Filters
||cdn4.userzoom.com^
||lp4.io^

but can you please explain me why I should add them when my data connection is slow?

Also, can you please explain the difference between these two:
 bypass_paywalls_clean-1.6.6.5-an+fx.xpi
bypass_paywalls_clean_lp-1.6.6.5-an+fx.xpi

Which one is best for Firefox?

Thank you very much!

**Comment by magnolia1234** [comment]
> but can you please explain me why I should add them when my data connection is slow?

Not your connection, but from the Corriere site to these Javascript-sources.
I think they're related to the popup-banners with recommendations (also lots of ads on Italian newspaper sites though).

LP-release was requested and needs less permissions (not all sites), but then you can't use custom sites.

**Comment by Kal999** [comment]
ok, thank you for the explanation. I guess I'd use the normal release (not LP). For now it seems Corriere is working again but I need to do more testing.
Thanks again a lot!

**Comment by magnolia1234** [comment]
PS Corriere is still working fine?
I might also block the extra scripts by BPC in a future release.

**Comment by Kal999** [comment]
Hi, yes it's working great! Thank you very very much!!!

**Comment by imdoubG** [comment]
It seems to work greatly! If don't work, a trick is to copy and paste the title of the article on the search bar of the site, removing any punctuation marks and reducing the title at the first words.
