### ISSUE TITLE
Custom: ilmessaggero.it

### ISSUE THREAD

**Issue by ciru86** [magnolia1234/bypass-paywalls-firefox-clean#37]
Hi, could it be possible to add "ilmessaggero.it", an Italian newspaper?
I tried to add it to custom sites, blocking Javascript and using googlebot, with no avail.
Anyway it is possible to read the entire article using outline.com or apple readability, so no hard paywall!
Thank you!

**Comment by magnolia1234** [comment]
You didn't enable the new custom site in (general) options, I guess?
Blocking Javascript or using Googlebot are not needed though (simple cookie-fix will do).

**Comment by ciru86** [comment]
You’re right, my fault!!
Thank you!!

**Comment by magnolia1234** [comment]
You're welcome.

**Comment by magnolia1234** [comment]
Site will also be added to next release.
