### ISSUE TITLE
Compiling xpi file

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-firefox-clean#39]
How does one compile an xpi file for your interim updates or do we have to wait for your new release?
As with Chrome version you can just download the new master.zip

**Comment by magnolia1234** [comment]
Well, you can change the extension of the master zip-file to xpi.
But then you've got a unsigned add-on, only works on mobile or desktop developer-release (allow unsigned add-ons).
It won't update though.
Btw mostly cosmetic UI changes in post-release commits.
