### ISSUE TITLE
New Request

### ISSUE THREAD

**Issue by kchio0331** [magnolia1234/bypass-paywalls-firefox-clean#4]
Hi,

Can you please make the following websites paywall free?

1) The Chronicle of Higher Education at https://www.chronicle.com
2) The Chinese version of Caixin Global at http://www.caixin.com
3) San Francisco Chronicle at https://www.sfchronicle.com/
4) Sacramento Bee at https://www.sacbee.com/

Please let me know your thought. Thank you!

**Comment by magnolia1234** [comment]
First two sites have a hard paywall (it seems), but the last two sites where just added while synchiing sites with the Chrome extension.

**Comment by kchio0331** [comment]
Hi magnolia1234,

Will you be able to add SF Chronicle and Sacramento Bee to Firefox extension? Thank you.

**Comment by magnolia1234** [comment]
I just did in add-on v1.6.4.0 (Chrome extension & Firefox add-on now support the same sites).

**Comment by kchio0331** [comment]
Thank you for your help!

**Comment by kchio0331** [comment]
Hi magnolia1234,

I think I am not able to read all SF Chronicle's articles paywall free with the latest 
v1.6.4.0 extension. I have taken a picture, and the link is at https://www.sfchronicle.com/local-politics/article/SF-official-arrested-by-FBI-was-go-to-guy-for-15011155.php. Can you please look into the problem? Thank you.
![Capture](https://user-images.githubusercontent.com/59630570/73384503-3cb58e80-4280-11ea-83bb-bb4649122317.PNG)

**Comment by kchio0331** [comment]
It is working now after I removed the cookies.
