### ISSUE TITLE
Cannot bypass paywall on sites like WSJ, or Barrons

### ISSUE THREAD

**Issue by dwwilli** [magnolia1234/bypass-paywalls-firefox-clean#41]
Hi 
Installed add on and its showing in my browser toolbar. 
However when I go to sites like WSJ or Barrons the paywall is still up. 
Can you help me?

**Comment by magnolia1234** [comment]
WSJ-fix in commits, but not yet in new release (later today).
Barrons needs fixing also now (same publisher)?

**Comment by magnolia1234** [comment]
Fixed in latest release v1.6.9.1.
