### ISSUE TITLE
cant access custom sites 

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-firefox-clean#44]
windows 10, mozilla firefox
when i press custom sites the button doesnt do anything so i cant access any settings of custom sites 
deleting and re-installing the add-on makes no difference
its weird
not sure if its to do with not having admin access on work pc, but custom sites works fine using the chrome addon

**Comment by magnolia1234** [comment]
Should work though, but maybe you can try to use add-on settings instead of icon/popup.

**Comment by danielgruber8** [comment]
Nope can't access custom sites in the settings either, 
Weird as it works on my regular pc, just not my work one...

**Comment by magnolia1234** [comment]
You have to check for errors in Firefox on your end.
Check about:debugging - inspect - select bpc - tab console.

**Comment by magnolia1234** [comment]
Update: check about:debugging - this firefox - bpc inspect - tab console.
Btw maybe old Firefox version?

**Comment by danielgruber8** [comment]
It is using Firefox Quantum 64.0
The debugging options are a bit different, this is what appears in the Console tab
Unchecked lastError value: Error: ID already exists: append ExtensionCommon.jsm:667
Unchecked lastError value: Error: ID already exists: convert ExtensionCommon.jsm:667
withLastError
resource://gre/modules/ExtensionCommon.jsm:667:9
create/<
chrome://browser/content/child/ext-menus.js:138:13

**Comment by danielgruber8** [comment]
Can't update to latest Firefox on work pc - no administrator access

**Comment by magnolia1234** [comment]
Some uncaught error, but it's not saying which one.
Can't you use a portable Firefox version?

**Comment by danielgruber8** [comment]
they dont allow usb sticks lol
