### ISSUE TITLE
Site request: https://www.elcomercio.pe

### ISSUE THREAD

**Issue by rnzdnyr** [magnolia1234/bypass-paywalls-firefox-clean#46]
Could you please add El Comercio to your list? Some articles, like the following: https://elcomercio.pe/politica/partidos/jne-la-carrera-por-reservar-el-nombre-de-lo-que-algun-dia-podria-ser-un-partido-politico-analisis-onpe-noticia/ are under paywall. Thank you very much in advance :)

**Comment by magnolia1234** [comment]
Will be added in new release.

**Comment by rnzdnyr** [comment]
Thank you very much!

**Comment by magnolia1234** [comment]
Already in Chrome extension (master-zip) though.
New FF addon in the weekend (probably).
