### ISSUE TITLE
New Site Request: The New Republic

### ISSUE THREAD

**Issue by inigma1** [magnolia1234/bypass-paywalls-firefox-clean#47]
Could you please add the site The New Republic (www.newrepublic.com)?

The link to the article is as follows:
https://newrepublic.com/article/157007/left-bigger-bernie-sanders

Thank you

**Comment by magnolia1234** [comment]
The site was added already in commit, but will be active in new release.
Btw have you switched to Firefox? ;-)

**Comment by inigma1** [comment]
Ah cool ! When do you think you would be able to launch the new release?

I use Firefox on my phone and Chrome on my computer. Firefox consumes more RAM on it. ;)

**Comment by magnolia1234** [comment]
Probably today.

**Comment by inigma1** [comment]
Okay, thank you
