### ISSUE TITLE
Doesn't work on Washington Post

### ISSUE THREAD

**Issue by Kaos-Industries** [magnolia1234/bypass-paywalls-firefox-clean#49]
Doesn't seem to work on this Washington Post link:

https://www.washingtonpost.com/local/police-say-suspect-foiled-monitoring-device/2013/01/26/8511de50-681b-11e2-85f5-a8a9228e55e7_story.html

**Comment by magnolia1234** [comment]
Still working fine for me though or do you get the anti-adblocker banner?

**Comment by Kaos-Industries** [comment]
Wow I'm an idiot and should pay more attention to what the modals are actually saying. Working perfectly, thanks.

**Comment by magnolia1234** [comment]
Modals?

**Comment by Kaos-Industries** [comment]
https://en.wikipedia.org/wiki/Modal_window

**Comment by magnolia1234** [comment]
Okay, you were confused then? ;-)
