### ISSUE TITLE
Paywall free for iPad's Firefox and the following websites

### ISSUE THREAD

**Issue by kchio0331** [magnolia1234/bypass-paywalls-firefox-clean#5]
Hello,

A. Will you be able to add the same bypass paywall extension to iPad's Firefox or Chrome? 

B. Will you be able to make the following websites paywall free?
   1) Modern Healthcare at https://www.modernhealthcare.com/
   2) Christian Science Monitor at https://www.csmonitor.com/
   3) National Geographic at https://www.nationalgeographic.com/
   4) Newsweek at https://www.newsweek.com/
   5) Time Magazine at https://time.com/
   6) National Review at https://www.nationalreview.com/
   7) National Affairs at https://www.nationalaffairs.com/
   8) Chinese version of Taiwan's Commonwealth Magazine at https://www.cw.com.tw/
   9) Chinese version of Taiwan's Global View Monthly magazine at https://www.gvm.com.tw/
   10) Chinese version of Harvard Business Review at https://www.hbrtaiwan.com/
   11) Hong Kong's Yazhou Zhoukan at http://www.yzzk.com/
   12) English version of China's academic database at http://new.oversea.cnki.net/index/
   13) English version of Taiwan's academic database at http://www.airitilibrary.com/Home/Index

Thank you for your help!

**Comment by magnolia1234** [comment]
No extensions on iPad, just cookie- and/or ad/scriptblockers.

For a list of 13 sites it would be helpfull to give an example of a paywalled article and the attempts you made to bypass the paywall (block cookie, javascript etc.).

**Comment by kchio0331** [comment]
Hi magnolia1234 ,

How can I add scriptblockers to iPad to make websites paywall free? Thank you.

**Comment by magnolia1234** [comment]
A combination of cookieblockers like NoCookie and scriptblockers like 1Blocker and/or AdGuard. No 'simple' fix like an extension/add-on.
PS 13 sites are for iPad also.

**Comment by kchio0331** [comment]
Hi magnolia1234,

I double checked some of the above websites. Some look like have paywall free features, some still do not. Please see the following individual articles.

1. Chinese version of Taiwan's Commonwealth Magazine: One article at https://www.cw.com.tw/article/article.action?id=5098666. I reached the daily article limit, so the website is blocking me. 
2. Chinese version of Harvard Business Review : One article at https://www.hbrtaiwan.com/article_content_AR0009424.html, I reached the daily article limit, so the website is blocking me. 
3. English version of China's academic database: I cannot access this article at http://new.oversea.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&filename=ZGFX201906003&dbname=CJFDAUTO
4. Hong Kong's Yazhou Zhoukan: After clicking on 3 articles, this article blocked my access with paywall. https://www.yzzk.com/article/details/%E4%B8%AD%E8%8F%AF%E5%A4%A9%E5%9C%B0/2020-05/1579578312841/%E5%86%8D%E9%80%A0%E4%B8%AD%E8%8F%AF%E6%B0%91%E5%9C%8B%E7%AA%81%E7%A0%B4%E9%81%B8%E6%B0%91%E7%B5%90%E6%A7%8B

Moreover, will you be able to have the following websites paywall free? 
1. Foreign Affairs: It has a paywall. Please see this article https://www.foreignaffairs.com/articles/united-states/2020-01-13/delicate-truce-us-chinese-trade-war
2. Project Syndicate: It has a paywall. Please see this article https://www.project-syndicate.org/bigpicture/china-global-economy-patient-zero?barrier=accesspaylog
3. World Politics Review: It has a paywall. Please see this article https://www.worldpoliticsreview.com/articles/28502/as-china-vietnam-relations-deteriorate-hanoi-mulls-closer-ties-with-the-u-s

Thank you again for your work!

**Comment by magnolia1234** [comment]
I've just added in v1.6.4.1: Harvard Business Review Taiwan, Modern Healthcare, National Review, The Christian Science Monitor and World Politics Review.
Foreign Affairs and Project Syndicate have a hard paywall though.
Do National Geographic, Newsweek and Time Magazine even have a paywall besides their subscription section?

**Comment by kchio0331** [comment]
Hi magnolia1234 ,

It looks like Newsweek and Time Magazine have paywalls for their subscription sections. Will you be able to break their paywalls? 

As to National Geographic, I see a paywall/subscription page here at https://www.nationalgeographic.com/history/reference/united-states-history/difference-between-caucus-primary-election/. After I enter my email, I can read the article. However, I cannot read the second and other articles on the website. Can you please look into the problem? 

Thank you for your work again!

**Comment by magnolia1234** [comment]
Just clicking 'continu reading' button will open the NG-article though.

**Comment by magnolia1234** [comment]
National Affairs has a hard paywall for premium articles (subscription-only).

**Comment by kchio0331** [comment]
This is fine then. Thank you.

**Comment by magnolia1234** [comment]
I've just added a commit for CommonWealth Magazine Taiwan (no release yet).
Hong Kong's Yazhou Zhoukan has premium articles and the mentioned academic databases have a hard paywall.
Btw Newsweek has no more paywall (new articles might have a delay though).

**Comment by kchio0331** [comment]
Thank you for your help again!
