### ISSUE TITLE
https://www.challenges.fr/ does not work

### ISSUE THREAD

**Issue by Wolsey20** [magnolia1234/bypass-paywalls-firefox-clean#50]
Hello,

The site https://www.challenges.fr/ does not work with firefox but works very well chrome.

Thanks.

**Comment by magnolia1234** [comment]
Indeed, in Firefox you also need to block the Javascript-file(s) from the site itself (not just paywall-script).
For now you can add a custom site with domain challenges.fr and enable block_javascript.
Images are hidden then, but this can be fixed later also.

**Comment by magnolia1234** [comment]
Fix-update in next release: images will be visible, but reactions/comments won't be loaded anymore (for non-premium articles you could disable site in options).
PS will you let me know if BPC also stops working in Chrome (no fix-update yet)?

**Comment by Wolsey20** [comment]
the chrome version works very well no problem

**Comment by magnolia1234** [comment]
I know Chrome works well, but that might change in the future.
I'm not a daily reader of French newspapers ;-)
