### ISSUE TITLE
Website Request: https://www.lefigaro.fr

### ISSUE THREAD

**Issue by Wolsey20** [magnolia1234/bypass-paywalls-firefox-clean#55]
Hello,

Could you please add the website https://www.lefigaro.fr ?

Thank you

**Comment by qnoum** [comment]
I've already asked some time ago. 
Unfortunately it uses hard paywall,
as well as mediapart and nouvelobs.

**Comment by Wolsey20** [comment]
thank you for your reply

**Comment by mrjohnson-tree** [comment]
.
