### ISSUE TITLE
eureka report

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-firefox-clean#56]
Happy Easter from Bugs Bunny
https://www.youtube.com/watch?v=n59YzfhI5p0

Can you unblock Eureka Report premium articles or is it hard paywall?

https://www.eurekareport.com.au/investment-news/us-employment-crash-the-search-for-a-bottom-vix-rule-policy-coordination-divi/147175

**Comment by magnolia1234** [comment]
Have you tried to add it as a custom site?
Googlebot-fix is working.
To be added later then.

**Comment by danielgruber8** [comment]
The site belongs to "Investsmart", maybe you can do a fix across their entire network of sites they have? Investsmart, Eureka Report, Intelligent Investor.... they might use the same paywall?
https://www.investsmart.com.au/
https://www.intelligentinvestor.com.au/
https://www.eurekareport.com.au

**Comment by danielgruber8** [comment]
PS: Do you ever read our Australian news at all? ;)

**Comment by danielgruber8** [comment]
How about an option to automatically use Googlebot and/or block javascript for ALL sites? 
Or can that stuff up pages?

**Comment by magnolia1234** [comment]
> The site belongs to "Investsmart", maybe you can do a fix across their entire network of sites they have? Investsmart, Eureka Report, Intelligent Investor.... they might use the same paywall?

Have you tested the other two too (as custom sites)?

**Comment by magnolia1234** [comment]
> How about an option to automatically use Googlebot and/or block javascript for ALL sites?
> Or can that stuff up pages?

Lots of sites block Googlebot and blocking Javascript can also disable menu and images/videos etc.

> PS: Do you ever read our Australian news at all? ;)

Sure, everyday ;-)

**Comment by danielgruber8** [comment]
i checked - googlebot also worked with intelligentinvestor.com.au
investsmart.com.au - just the company who runs those pages so nothing to be added

**Comment by danielgruber8** [comment]
I was too quick.
Googlebot fix for eurekareport.com.au DOES unblock the text of the article 
The audio comes up as a 403 forbidden when trying to play... so maybe you need to do extra magic?
https://www.eurekareport.com.au/investment-news/you-cant-negotiate-with-a-virus/147197

**Comment by magnolia1234** [comment]
You can open the audio by clicking i-badge & more info.
Not sure if the issue is caused by Googlebot-fix.

**Comment by magnolia1234** [comment]
Just added: Eureka Report & Intelligent Investor.

**Comment by danielgruber8** [comment]
Can you please add https://switzersuperreport.com.au/ as well (Googlebot fix)? 
Peter Switzer is a very popular financial journalist.

Did you have any luck fixing that 403 forbidden with the audio (besides clicking on the "i" button)?

**Comment by magnolia1234** [comment]
> Did you have any luck fixing that 403 forbidden with the audio (besides clicking on the "i" button)?

Audio-error is indeed caused by Googlebot-fix. When you disable BPC without refreshing you can play the embedded audio though.
Maybe I can add a weblink to external audio later.
