### ISSUE TITLE
custom sites sort order

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-firefox-clean#57]
I added Eureka Report to custom sites but it didn't sort it alphabetically in the custom sites ?

{"Geelong Advertiser":{"domain":"geelongadvertiser.com.au","googlebot":"1"},"Maitland Mercury":{"domain":"maitlandmercury.com.au"},"Eureka Report":{"domain":"eurekareport.com.au","googlebot":"1"}}

**Comment by magnolia1234** [comment]
> I added Eureka Report to custom sites but it didn't sort it alphabetically in the custom sites ?

Indeed, maybe I'll sort the custom sites in options in the future.
PS good to see you figured out the custom sites :-)

**Comment by danielgruber8** [comment]
Seems switzersuperreport.com.au works with Googlebot fix

No luck with https://rivkin.com.au/members/resources/strategies/asx-event-strategy or https://www.fnarena.com/index.php/financial-news/australian-broker-call/

Also you have to delete the site and start over if you want to edit googlebot / block javascript for a site already added.... there should be an edit button in the list....

**Comment by magnolia1234** [comment]
> Also you have to delete the site and start over if you want to edit googlebot / block javascript for a site already added.... there should be an edit button in the list....

For now you can edit the bottom json-text, for example googlebot:0 etc.
PS free Australian beer should also be added ;-)

**Comment by magnolia1234** [comment]
Rivkin and FnArena indeed have a hard paywall (subscription-only).
Which of the other financial sites are of interest to 'regular' users?

**Comment by magnolia1234** [comment]
Just added: sort custom sites (json).

**Comment by danielgruber8** [comment]
You're a very busy Easter Bunny :)
