### ISSUE TITLE
Websites Request : lexpress.fr, lequipe.fr and causeur.fr

### ISSUE THREAD

**Issue by Wolsey20** [magnolia1234/bypass-paywalls-firefox-clean#58]
Hello,

Could you please add these three websites :

https://www.lexpress.fr/
https://www.lequipe.fr/
https://www.causeur.fr/

Thank you

**Comment by magnolia1234** [comment]
Have you tried to add them as custom site?

**Comment by Wolsey20** [comment]
I tried but it doesn't work

**Comment by magnolia1234** [comment]
Premium articles have a hard paywall (subscription-only).
