### ISSUE TITLE
I can no longer order pizza when this extension is loaded.

### ISSUE THREAD

**Issue by 7LRX** [magnolia1234/bypass-paywalls-firefox-clean#6]
(No, I haven't been drinking!)

With all my Windows 10/FF extensions disabled (except BPC), I go to dominos.com, enter my zip code, then select my nearest location, and the Dominos icon will sit there and spin forever.

Everything works fine after disabling BPC.

This did not happen as of 1.6.2 of the BP extension, so I do not know if it's a "feature" of any BPC version or just the newly-released 1.6.4.1

**Comment by magnolia1234** [comment]
No problem here, probably timeout because of bad connection.
