### ISSUE TITLE
Website Request: Addition of New Scientist

### ISSUE THREAD

**Issue by inigma1** [magnolia1234/bypass-paywalls-firefox-clean#7]
Hello,

Could you please unblock the paywall for this website called the New Scientist?

For instance, I am unable to read the following article:
https://www-newscientist-com.cdn.ampproject.org/v/s/www.newscientist.com/article/2192256-genome-sequencing-could-become-a-routine-part-of-health-care-in-the-uk/amp/?amp_js_v=a2&amp_gsa=1&usqp=mq331AQCKAE%3D#aoh=15809799984823&referrer=https%3A%2F%2Fwww.google.com&amp_tf=From%20%251%24s&ampshare=https%3A%2F%2Fwww.newscientist.com%2Farticle%2F2192256-genome-sequencing-could-become-a-routine-part-of-health-care-in-the-uk%2F

However, I am able to access the following:
https://www.newscientist.com/article/2187499-uk-dna-project-hits-major-milestone-with-100000-genomes-sequenced/

**Comment by magnolia1234** [comment]
Premium-articles have a hard paywall (subscription-only).
