### ISSUE TITLE
React News 

### ISSUE THREAD

**Issue by asoksevil** [magnolia1234/bypass-paywalls-firefox-clean#8]
https://reactnews.com/

You can actually access by just using the cached version of Google however if this were to be incorporated it would be much more convenient.

Thanks

**Comment by kingkong914** [comment]
Google cache works only for a few articles though.

**Comment by magnolia1234** [comment]
Fix with Googlebot not working though.
Google cache also not working for all articles (mostly for articles copied from other sites).
